allow embedded message field with empty name
alta/protopatch pull request #56
Opened 2021-06-25 12:03 UTC by Adphi

Add embedding support by setting the `(go.field).name` to an empty string.
Example: 
```protobuf
message MessageWithEmbeddedFields {
  Embedded message = 1 [(go.field).name = ''];
}

message Embedded {
  string message = 1;
}
```

2021-06-25 20:51 UTC, ydnar commented
Wow, interesting. Some quick feedback, as I'm on my phone:

- I'd prefer the API to be explicit rather than implicit based on an empty name, e.g.: `go.field.embedded = true`
- Can you revert the formatting changes in the proto files that aren't relevant to this PR?
- Tests should exist and pass.

Thanks for the PR!

2021-06-26 13:45 UTC, Adphi commented
I agree with with you on explicit over explicit (I didn't want change the defined API). 
I added the `go.field.embedded` message option. 
I will revert formatting changes.

2021-06-26 20:03 UTC, Adphi commented
@ydnar do you want to explicitly fail on unsupported options annotation, like oneof field annotated as embedded or non message type annotated as embedded or just silently ignore these unsupported options?

2021-06-26 22:10 UTC, ydnar commented
> @ydnar do you want to explicitly fail on unsupported options annotation, like oneof field annotated as embedded or non message type annotated as embedded or just silently ignore these unsupported options?

Explicitly fail with a verbose error message.

2021-06-26 22:15 UTC, ydnar commented on tests/message/message_renames.proto
> +  option (go.message).name = 'Frank';
Please format these consistently with the existing files. I use the clang-format extension in VS Code to automatically format proto files according to the spec in `.clang-format`.

2021-06-26 22:17 UTC, ydnar commented on tests/message/message_renames.proto
> +message MessageWithEmbeddedFields {
I’d break apart these into discrete messages for each behavior you want to validate. Also, it might be confusing to have a type called `message`.

2021-06-28 18:01 UTC, Adphi commented
> > @ydnar do you want to explicitly fail on unsupported options annotation, like oneof field annotated as embedded or non message type annotated as embedded or just silently ignore these unsupported options?
> 
> Explicitly fail with a verbose error message.

I agree with you, but I can see some limitations based on the existing API... 
None of the `scan` methods returns an error, which does not allow validation of protobuf options, this would lead to an ugly `os.Exit(code)`, inside one of the scan methods, the logger output beeing redirected to `io.Discard` by default if `PROTO_PATCH_DEBUG_LOGGING` is not defined, the `log.Fatal` message would not reach the user...  I think the problem should be addressed in separated issue / pull request.

2021-07-03 00:42 UTC, Adphi commented
Ping @ydnar

2021-07-03 01:38 UTC, ydnar commented
> Ping @ydnar

Hey there—we’re on vacation for the July 4th weekend. I’ll take a look at the PR next week when we’re back home!

2021-09-20 15:04 UTC, ydnar requested changes
Hi there, thanks for your patience. I’d love to see this merged with a couple changes.

2021-09-20 15:04 UTC, ydnar commented on patch/patcher.go
> +	embedded := f.Message != nil && f.Oneof == nil && opts.GetEmbedded()
Log a warning here if user tries to embed a non-message or oneof field.

2021-09-20 15:04 UTC, ydnar commented on patch/patcher.go
> +	embedded := f.Message != nil && f.Oneof == nil && opts.GetEmbedded()
```suggestion
	embed := f.Message != nil && f.Oneof == nil && opts.GetEmbedded()
```

2021-09-20 15:04 UTC, ydnar commented on patch/patcher.go
> +func (p *Patcher) RenameField(id protogen.GoIdent, newName string, embedded bool) {
```suggestion
func (p *Patcher) RenameField(id protogen.GoIdent, newName string, embed bool) {
```

2021-09-20 15:04 UTC, ydnar commented on patch/go.proto
> +	optional bool embedded = 2;
With fresh eyes, I think the verb form of `embed` makes sense here in the options API.

```suggestion
	optional bool embed = 2;
```

2021-09-20 15:07 UTC, Adphi commented
Hi @ydnar !
Thanks for you reply. I'll make the requested changes as soon as I can.
FYI: I started to work on the "casttype" implementation 😃

2021-09-20 15:08 UTC, ydnar commented
> FYI: I started to work on the "casttype" implementation 😃

Wow, I’m curious to see how that works.

2021-09-21 15:49 UTC, ydnar commented on patch/go.proto
> +	// Only message types are allowed to be embedded, oneof fields are not embeddable.
```suggestion
	// The embed option indicates the field should be embedded in the generated Go struct.
	// Only message types can be embedded. Oneof fields cannot be embedded.
	// See https://golang.org/ref/spec#Struct_types.
```

2021-09-21 15:50 UTC, ydnar commented on patch/patcher.go
> +	embed := f.Message != nil && f.Oneof == nil && opts.GetEmbed()
This still needs a warning log if user attempts to embed a non-message or a oneof field.

2021-09-21 15:52 UTC, ydnar commented on patch/patcher.go
> +	if embed {
This should be moved above line 277 where it attempts to lint the `newName`. Please make this change and add a test case for linting an embedded field.

2021-09-22 18:01 UTC, ydnar requested changes

2021-09-22 18:01 UTC, ydnar commented on tests/message/message_test.go
> +	var _ *Embedded = m.Embedded
Should also test that `m.Message == "noop"` to validate the embed.

2021-09-22 18:18 UTC, Adphi commented on tests/lint/lint_test.go
> +func Test(t *testing.T) {
oops sorry, I forgot to rename that...

2021-09-23 16:23 UTC, ydnar commented on tests/lint/lint_test.go
> +		IDFieldsTest: &IDFieldsTest{
These message names still have the word `Test` in it.

2021-09-23 17:08 UTC, Adphi commented on tests/lint/lint_test.go
> +		IDFieldsTest: &IDFieldsTest{
sorry misread the previous comment... it's fixed.

2021-09-23 17:22 UTC, ydnar approved these changes

2021-09-23 17:22 UTC, merged